config/routes.rb
Rails.application.routes.draw do
  

  resources :docs

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  devise_for :agents, controllers: {
        sessions: 'agents/sessions',
        registrations: 'agents/registrations'
      }
  devise_for :users, controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations'
      }
  resources :students
  resources :levels
  resources :courses

  root 'welcome#index'

  get  'users/sign_up'   => 'users/registrations#new'

  resources :contacts
  

  get 'about' => 'welcome#about'

  get 'listings' => 'welcome#listings'

  get 'apply-online' => 'students#new'

  post "apply-online", to: "students#create"
  put "apply-online", to: "students#update"
  match "apply-online" => "students#create", :via => "post"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/student.rb
class Student < ApplicationRecord

	validates :fname, presence: true, length: { minimum: 3 }
	validates :lname, presence: true, length: { minimum: 5 }


	validates :email, :presence => true, :uniqueness => true, format: { with: /\A[^@\s]+@([^@.\s]+\.)+[^@.\s]+\z/ }
	validates :phone, numericality: { only_integer: true }, length: { minimum: 10 }

	def to_s
		"#{fname} #{lname}"
	end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]
  before_filter :ensure_admin, only: [:index]
  before_action :authenticate_user!, except: :index

  # GET /students
  # GET /students.json
  def index
    @students = Student.all
  end

  # GET /students/1
  # GET /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to new_contact_path, notice: 'Application Received! We will contact you shortly. You may leave us a message if you have any questions or comments. Thank You for Applying With GETC.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:fname, :lname, :level, :course, :nationality, :email, :phone, :countryloc)
    end

    def ensure_admin
      unless current_user && current_user.admin?
       render :text => "What are you doing with your life?", :status => :unauthorized
      end
    end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/edit.html.erb
<div id="contentBk" class="clearfix">
        <div id="content">
            <div class="topImg clearfix">
                <%= image_tag("headers/header_1.jpg", :alt => "About Us") %>
                <p>Contact <strong>Us</strong></p>
            </div>
                <div class="wrapper">
                    <div class="boxInfo contactForm apply-now">


<h1>Editing Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>


</div>                    
                    
                <div class="clear"></div>

                    
                
        </div>
</div>

app/views/students/index.html.erb
<div id="contentBk" class="clearfix">
            <div id="content">
                <div class="topImg clearfix">
                    <%= image_tag("headers/header_1.jpg", :alt => "Course Listings") %>
                    <p>Student <strong>Listings</strong></p>
                </div>
                <div class="wrapper">
                    <p id="notice"><%= notice %></p>

                            <h1>List of All Students</h1>

                            <table>
                              <thead>
                                <tr>
                                  <th>First Name</th>
                                  <th>Last Name</th>
                                  <th>Degree Type</th>
                                  <th>Courses</th>
                                  <th>Nationality</th>
                                  <th>Email</th>
                                  <th>Phone</th>
                                  <th>Choice of Study</th>
                                  <th colspan="3"></th>
                                </tr>
                              </thead>

                              <tbody>
                                <% @students.each do |student| %>
                                  <tr>
                                    <td><%= student.fname %></td>
                                    <td><%= student.lname %></td>
                                    <td><%= student.level.leveltype %></td>
                                    <td><%= student.course.coursename %></td>
                                    <td><%= student.nationality %></td>
                                    <td><%= student.email %></td>
                                    <td><%= student.phone %></td>
                                    <td><%= student.countryloc %></td>
                                    <td><%= link_to 'Show', student %></td>
                                    <td><%= link_to 'Edit', edit_student_path(student) %></td>
                                    <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                                  </tr>
                                <% end %>
                              </tbody>
                            </table>

                            <br>

                            <%= link_to 'New Student', new_student_path %>


                    <div class="clear"></div>

                    
                </div>


            </div>
        </div>

app/views/students/new.html.erb
<section id="about">
  <div class="container">

      <div class="row">
        <div class="col-md-8 col-md-offset-2">
          <div class="well">
          <p class="notice alert"><%= notice %></p>
          <p class="alert"><%= alert %></p>
            <h1>Apply Online :: Registration Form</h1>

            <%= render 'form', student: @student %>
          </div>
        </div>
        
      </div>

  </div>
</section>

app/views/students/show.html.erb
<div id="contentBk" class="clearfix">
        <div id="content">
            <div class="topImg clearfix">
                <%= image_tag("headers/header_1.jpg", :alt => "About Us") %>
                <p>Contact <strong>Us</strong></p>
            </div>
                <div class="wrapper">
                    <div class="boxInfo contactForm apply-now">

<p id="notice"><%= notice %></p>

<p>
  <strong>Fname:</strong>
  <%= @student.fname %>
</p>

<p>
  <strong>Lname:</strong>
  <%= @student.lname %>
</p>

<p>
  <strong>Level:</strong>
  <%= @student.level_id %>
</p>

<p>
  <strong>Course:</strong>
  <%= @student.course_id %>
</p>

<p>
  <strong>Nationality:</strong>
  <%= @student.nationality %>
</p>

<p>
  <strong>Email:</strong>
  <%= @student.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @student.phone %>
</p>

<p>
  <strong>Countryloc:</strong>
  <%= @student.countryloc %>
</p>

<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path %>



                  </div>                    
                    
                <div class="clear"></div>

                    
                
        </div>
</div>