config/routes.rb
Rails.application.routes.draw do
  

  resources :docs

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  devise_for :agents, controllers: {
        sessions: 'agents/sessions',
        registrations: 'agents/registrations'
      }
  devise_for :users, controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations'
      }
  resources :students
  resources :levels
  resources :courses

  root 'welcome#index'

  get  'users/sign_up'   => 'users/registrations#new'

  resources :contacts
  

  get 'about' => 'welcome#about'

  get 'listings' => 'welcome#listings'

  get 'apply-online' => 'students#new'

  post "apply-online", to: "students#create"
  put "apply-online", to: "students#update"
  match "apply-online" => "students#create", :via => "post"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/doc.rb
class Doc < ApplicationRecord
	belongs_to :agent
	validates :title, presence: true
	validates :description, presence: true

	mount_uploader :document, DocumentUploader
end

app/controllers/docs_controller.rb
class DocsController < ApplicationController
	before_action :authenticate_agent!
	before_action :find_doc, only: [:show, :edit, :update, :destroy]

  def index
  	@docs = current_agent.docs.all.order("created_at DESC")
  end

  def new
  	@doc = current_agent.docs.build
  end

  def create
  	@doc = current_agent.docs.build(doc_params)

  	if @doc.save
  		flash[:notice] = "Document Posted Successfully"
  		redirect_to @doc
  	else
  		flash[:alert] = "Problem occured while saving..."
  		render 'new'
  	end
  end

  def edit

  end

  def update
  	
  	if @doc.update(doc_params)
  		redirect_to @doc, notice: "Document Posted Successfully"
  	else
  		flash[:alert] = "Problem occured while saving..."
  		render 'edit'
  	end
  end

  def show
  end

  def destroy
  	@doc.destroy
  	redirect_to docs_path
  end

  private

  def find_doc
  	@doc = Doc.find(params[:id])
  end

  def doc_params
  	params.require(:doc).permit(:title, :description, :document)
  end

  
end

app/helpers/docs_helper.rb
module DocsHelper
end

app/views/docs/_form.html.erb
<%= bootstrap_form_for @doc do |f| -%>
	<%= f.text_field :title, label: "Title" -%>
	<%= f.text_area :description, label: "Description" -%>
	<%= f.file_field :document, label: "Upload Document(s)" -%> <p><small>Only jpg, jpeg, png and pdf file extensions are allowed.</small></p>
	<%= f.submit "Post Document" -%>
<% end -%>

app/views/docs/edit.html.erb
<div class="container">
	<div class="page-header">
		<h1 class="text-center">Edit Submitted Document</h1>
	</div>

	<div class="row">
		<div class="col-md-6 col-md-offset-3">
			<%= render 'form' -%>
		</div>
	</div>
</div>

app/views/docs/index.html.erb
<%= content_for :title, 'Global Edutech Trading & Consultancy | All Document Listings' %>

<div class="container">
	<div class="page-header">
		<h1 class="text-center">All Documents</h1>
	</div>

	<div class="row">
		<div class="col-md-6 col-md-offset-3">
			<div class="well">
				<% @docs.each do |doc| -%>
						<h2><%= link_to doc.title, doc_path(doc)-%></h2>
						<small>submitted <%= time_ago_in_words(doc.created_at) -%> ago by <%= current_agent.name -%></small>
						<p><%= truncate(doc.description, { length: 30 })  -%></p>
				<% end -%>
			</div>
			
		</div>
	</div>
</div>

app/views/docs/new.html.erb
<%= content_for :title, 'Global Edutech Trading & Consultancy | Submit Documents' %>

<div class="container">
	<div class="page-header">
		<h1 class="text-center">New Document Submission</h1>
	</div>

	<div class="row">
		<div class="col-md-6 col-md-offset-3">
			<div class="well">
				<p class="notice alert-success"><%= notice %></p>
    <p class="alert"><%= alert %></p>
				<%= render 'form' -%>
			</div>
			
		</div>
	</div>
</div>

app/views/docs/show.html.erb
<%= content_for :title, 'Global Edutech Trading & Consultancy | Show Document' %>

<div class="container">

	<div class="row">
		<div class="col-md-8 col-md-offset-2">
		<p class="notice alert-success text-center"><%= notice %></p>
          <p class="alert text-center"><%= alert %></p>
			<h2><%= @doc.title -%></h2>

			<p><%= @doc.description -%></p>

			<%= link_to image_tag(@doc.document, class: "img-thumbnail docImg"), @doc.document.url -%>
			<br><br>
			<%= link_to "Back", docs_path -%> |
			<%= link_to "Edit Document", edit_doc_path(@doc) -%> | 
			<%= link_to "Delete Document", doc_path, method: :delete, data: { confirm: "Are you sure?" } -%>
		</div>
	</div>
</div>