config/routes.rb
Rails.application.routes.draw do
  

  resources :docs

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  devise_for :agents, controllers: {
        sessions: 'agents/sessions',
        registrations: 'agents/registrations'
      }
  devise_for :users, controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations'
      }
  resources :students
  resources :levels
  resources :courses

  root 'welcome#index'

  get  'users/sign_up'   => 'users/registrations#new'

  resources :contacts
  

  get 'about' => 'welcome#about'

  get 'listings' => 'welcome#listings'

  get 'apply-online' => 'students#new'

  post "apply-online", to: "students#create"
  put "apply-online", to: "students#update"
  match "apply-online" => "students#create", :via => "post"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
	<title>
  	<%= content_for :title || 'Global Edutech Trading & Consultancy | Home' %>
	</title>
	<%= csrf_meta_tags %>
	<meta name="description" content="Global Edutech Trading &amp; Consultancy. Edutech Global. Study Agency in Kuala Lumpur, Malaysia. Study Abroad. Apply Online">
  <meta name="keywords" content="Global Edutech Trading &amp; Consultancy, Study Abroad, Study Agency in Kuala Lumpur, Students Services, International Study Agent, Study Abroad Malaysia">
  <meta name="Yinka Ash" content="iamyinka.com">
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

	<div id="logo">
	  <%= link_to(image_tag("logo.png", :alt => "Logo"), root_path) %>
	</div>
	<nav class="navbar navbar-inverse">
	  <div class="container">
		<div class="navbar-header">
		  <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
			<span class="sr-only">Toggle navigation</span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
		  </button>
		</div>
		<div id="navbar" class="collapse navbar-collapse">
		  <ul class="nav navbar-nav">
			<li>
				<%= link_to root_path do %> 
					<i class="fa fa-home"></i>
						Home
				<% end -%>
			</li>

			<li>
		   <%= link_to about_path do %>
		   	<i class="fa fa-users"></i>
					About GETC
				<% end -%>
		   </li>

			<% if user_signed_in? %>

				<li>
					<%= link_to apply_online_path do %> 
					<i class="fa fa-sign-in"></i>
						Online Application
					<% end -%>
				</li>
				<li>
				<%= link_to destroy_user_session_path, method: :delete do %>
					<i class="fa fa-unlock-alt"></i>
					Log Out
				<% end -%>
				</li>
			
			
			<% elsif !current_user && !current_agent -%>
				<li>
					<%= link_to new_user_registration_path do %> 
					<i class="fa fa-sign-in"></i>
						Apply Online
					<% end -%>
				</li>
			<% end -%>

			
				

				<li>
					<%= link_to listings_path do %> 
					<i class="fa fa-list-alt"></i>
						Agent Listings
					<% end -%>
				</li>
				
		
		  </ul>

		   <ul class="nav navbar-nav navbar-right">
		   
		   

			
			<% if agent_signed_in? %>
				<li>
					<%= link_to new_doc_path do %>
						<i class="fa fa-check"></i>
						Submit Documents
					<% end -%>
				</li>

				<li>
					<%= link_to docs_path do %>
						<i class="fa fa-list"></i>
						All Documents
					<% end -%>
				</li>

				<li>
				<%= link_to destroy_agent_session_path, method: :delete do %>
					<i class="fa fa-unlock-alt"></i>
					Sign Out
				<% end -%>
				</li>
				<% elsif !current_user -%>
			<li>

				<%= link_to new_agent_session_path do %> 
				<i class="fa fa-lock"></i>
					Agent Login
				<% end -%>
			</li>
			<% end %>

			<li>
				<%= link_to new_contact_path do %> 
				<i class="fa fa-envelope"></i>
					Contact Us
				<% end -%>
			</li>
			
		  </ul>
		</div><!--/.nav-collapse -->
	  </div>
	</nav>   
		
	   
	<%= yield %>

	<hr>
	<footer>
	  <div class="container">
		<p class="pull-left">&copy; 2017 Copyright GETC.</p>
		<p class="pull-right">Creative Design By: <a href="#">Yinka Ash</a></p>
	  </div>
	</footer>

  </body>
</html>